version: "3.8"

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: stacky_nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - nginx-reverse-proxy
  portainer:
    image: portainer/portainer-ce
    container_name: stacky_portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    expose:
      - 9000
    environment:
      VIRTUAL_PORT: "9000"
      VIRTUAL_HOST: ${PORTAINER_HOST:-portainer.localhost}
      LETSENCRYPT_HOST: ${PORTAINER_HOST:-portainer.localhost}
    depends_on:
      - nginx-proxy
    networks:
      - nginx-reverse-proxy

volumes:
  html:
  vhost:
  certs:
  portainer_data:

networks:
  nginx-reverse-proxy:
    name: nginx-reverse-proxy
