version: "3.8"

services:
  acme-companion:
    image: nginxproxy/acme-companion
    container_name: stacky_acme-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: "abdennour@abbi-studio.fr"
    depends_on:
      - nginx-proxy
    networks:
      - nginx-reverse-proxy

volumes:
  acme:

networks:
  nginx-reverse-proxy:
    name: nginx-reverse-proxy
